// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvkg_nSPGmaJCcVD6ge6WmawbQhEq6bk',
    appId: '1:718597555031:web:3d62b55b614f257562f412',
    messagingSenderId: '718597555031',
    projectId: 'burl-ad60f',
    authDomain: 'burl-ad60f.firebaseapp.com',
    storageBucket: 'burl-ad60f.firebasestorage.app',
    measurementId: 'G-B8QSG9TMVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkVo1IzZRGXyMZjLbnhLSg59-DD1Chcw',
    appId: '1:718597555031:android:ca970f95115285e862f412',
    messagingSenderId: '718597555031',
    projectId: 'burl-ad60f',
    storageBucket: 'burl-ad60f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiFBPTXI6uSxhFX0LCrz210xazQnrsvv0',
    appId: '1:718597555031:ios:d301546333fec65762f412',
    messagingSenderId: '718597555031',
    projectId: 'burl-ad60f',
    storageBucket: 'burl-ad60f.firebasestorage.app',
    iosBundleId: 'com.example.cricketcoachflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiFBPTXI6uSxhFX0LCrz210xazQnrsvv0',
    appId: '1:718597555031:ios:d301546333fec65762f412',
    messagingSenderId: '718597555031',
    projectId: 'burl-ad60f',
    storageBucket: 'burl-ad60f.firebasestorage.app',
    iosBundleId: 'com.example.cricketcoachflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhvkg_nSPGmaJCcVD6ge6WmawbQhEq6bk',
    appId: '1:718597555031:web:721c0ffa8e47fa8e62f412',
    messagingSenderId: '718597555031',
    projectId: 'burl-ad60f',
    authDomain: 'burl-ad60f.firebaseapp.com',
    storageBucket: 'burl-ad60f.firebasestorage.app',
    measurementId: 'G-MYWPZ06LVQ',
  );
}
